name: checkov
on:
  pull_request:
  push:
    branches:
      - main
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: read-all

jobs:
  scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for GitHub/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run checkov
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        enable_secrets_scan_all_files: true
        output_format: cli,sarif
        output_file_path: console,results.sarif
        download_external_modules: true
        #soft_fail: true
        #api-key: ${{ secrets.BC_API_KEY }}
      #env:
        #PRISMA_API_URL: https://api4.prismacloud.io

    - name: Upload SARIF file
      uses: GitHub/codeql-action/upload-sarif@v3

      # Results are generated only on a success or failure
      # this is required since GitHub by default won't run the next step
      # when the previous one has failed. Alternatively, enable soft_fail in checkov action.
      if: success() || failure()
      with:
        sarif_file: results.sarif
